apiVersion: tekton.dev/v1
kind: Pipeline
metadata:
  name: build-pipeline
spec:
  tasks:
  - name: clone-repository
    taskRef:
      params:
      - name: name
        value: git-clone-oci-ta
      - name: bundle
        value: quay.io/mytestworkload/task-git-clone-oci-ta:0.1@sha256:0bafd44735ac634a88928d8b9d31e3fc738635a5f0bb79c69a9eb761ef94879c
      - name: kind
        value: task
      resolver: bundles
    params:
    - name: url
      value: $(params.git-url)
    - name: revision
      value: $(params.revision)
  - name: build-container
    taskRef:
      params:
      - name: name
        value: buildah-oci-ta
      - name: bundle
        value: quay.io/mytestworkload/task-buildah-oci-ta:0.3@sha256:24cb41782c21ffbf7a953a5d6b4e1ec2914d3b8fc7e0d3f5db3c3a04aeb785cf
      - name: kind
        value: task
      resolver: bundles
    runAfter:
    - clone-repository
  - name: summary
    taskRef:
      params:
      - name: name
        value: summary
      - name: bundle
        value: quay.io/mytestworkload/task-summary:0.2@sha256:9caf293f1049739e8c4e40ac84ba532388279a8d558877e7a47d0fcfc2045d42
      - name: kind
        value: task
      resolver: bundles
    runAfter:
    - build-container
  - name: apply-tags
    runAfter:
    - build-container
    taskRef:
      resolver: bundles
      params:
      - name: name
        value: apply-tags
      - name: kind
        value: task
      - name: bundle
        value: quay.io/mytestworkload/task-apply-tags:0.1@sha256:c72d34ffb01a9340ed3783483945d0c497da194a8e2443fa338671b94a252031
