apiVersion: tekton.dev/v1
kind: Pipeline
metadata:
  name: build-pipeline
spec:
  tasks:
  - name: clone-repository
    taskRef:
      params:
      - name: name
        value: git-clone
      - name: bundle
        value: quay.io/mytestworkload/task-git-clone:0.1@sha256:02b649f4cc17e5927e0189febed2ca7603e9eb0ef666bc0b0ab28b807f612566
      - name: kind
        value: task
      resolver: bundles
    params:
    - name: url
      value: $(params.git-url)
    - name: revision
      value: $(params.revision)
  - name: build-container
    taskRef:
      params:
      - name: name
        value: buildah
      - name: bundle
        value: quay.io/mytestworkload/task-buildah:0.3@sha256:73dc42ef3d93860cf1e822f1feef69bf553cbfb495e120aebd776298af42b2f5
      - name: kind
        value: task
      resolver: bundles
    runAfter:
    - clone-repository
  - name: summary
    taskRef:
      params:
      - name: name
        value: summary
      - name: bundle
        value: quay.io/mytestworkload/task-summary:0.2@sha256:e46d195504cfd67483d5346540cddcaae6878f724bc49fb454cb7ebcc2dcfb5f
      - name: kind
        value: task
      resolver: bundles
    runAfter:
    - build-container
  - name: apply-tags
    runAfter:
    - build-container
    taskRef:
      resolver: bundles
      params:
      - name: name
        value: apply-tags
      - name: kind
        value: task
      - name: bundle
        value: quay.io/mytestworkload/task-apply-tags:0.1@sha256:1731b51f98421319acf5091a5c72eb841b85aaf3c663e0d5a7bb6a9e3bada45a
  - name: deprecated-image-check
    runAfter:
    - build-container
    taskRef:
      resolver: bundles
      params:
      - name: name
        value: deprecated-image-check
      - name: kind
        value: task
      - name: bundle
        value: quay.io/mytestworkload/task-deprecated-image-check:0.4@sha256:68a3a6dc41a9678e0cab5ac58783fb6f3011f3d27d6dbc1d1562e22d13a0afff
  - name: clair-scan
    runAfter:
    - build-container
    taskRef:
      resolver: bundles
      params:
      - name: name
        value: clair-scan
      - name: kind
        value: task
      - name: bundle
        value: quay.io/mytestworkload/task-clair-scan:0.2@sha256:3aa8e50f0526e277832b7b729d6d3b3155e2d6cd274f4387bebb565c0275ab5c
    when:
    - input: $(params.skip-checks)
      operator: in
      values:
      - "false"
  - name: sast-snyk-check
    taskRef:
      resolver: bundles
      params:
      - name: name
        value: sast-snyk-check
      - name: kind
        value: task
      - name: bundle
        value: quay.io/mytestworkload/task-sast-snyk-check:0.3@sha256:0da152daeac3dd28d1f7264d941f8c05d2f3500eecd77332170a2319c65f1112
    when:
    - input: $(params.skip-checks)
      operator: in
      values:
      - "false"
  - name: push-dockerfile
    taskRef:
      resolver: bundles
      params:
      - name: name
        value: push-dockerfile
      - name: kind
        value: task
      - name: bundle
        value: quay.io/mytestworkload/task-push-dockerfile:0.1@sha256:2b870c1ada95756a1dd5c432ff807185f2f797818d38612c336decfa568ae526
  - name: show-sbom
    taskRef:
      resolver: bundles
      params:
      - name: name
        value: show-sbom
      - name: kind
        value: task
      - name: bundle
        value: quay.io/mytestworkload/task-show-sbom:0.1@sha256:e112e4e951ca70e7833376b36aa272b4c64adfde55b2ce0b7d6eaf15604e81e2
  - name: prefetch-dependencies
    taskRef:
      resolver: bundles
      params:
      - name: name
        value: prefetch-dependencies
      - name: kind
        value: task
      - name: bundle
        value: quay.io/mytestworkload/task-prefetch-dependencies:0.1@sha256:6d4847167442b084230aceb69cef26b52d2d5cefcbf3098d3c6fc2b102445dc9
  - name: clamav-scan
    taskRef:
      resolver: bundles
      params:
      - name: name
        value: clamav-scan
      - name: kind
        value: task
      - name: bundle
        value: quay.io/mytestworkload/task-clamav-scan:0.2@sha256:0df33616ccbfba2f7ada454f2b71df40ff695961321008e5fe4a9ddb0c957a12
    when:
    - input: $(params.skip-checks)
      operator: in
      values:
      - "false"
  params:
  - name: git-url
    type: string
  - name: revision
    type: string
  - name: output-image
    type: string
  - name: skip-checks
    type: string
