apiVersion: tekton.dev/v1
kind: Pipeline
metadata:
  name: ci-pipeline
spec:
  tasks:
  - name: clone
    params:
    - name: url
      value: "https://github.com/konflux-ci/pipeline-migration-tool"
    taskRef:
      params:
      - name: name
        value: clone
      - name: bundle
        value: quay.io/mytestworkload/build-definitions-test/task-clone:0.2@sha256:ae3d50ab78b21bddd6582daa4dd266c8d4bfab2f8fcf0f259318049f859845c9
      - name: kind
        value: task
      resolver: bundles
  - name: lint
    taskRef:
      params:
      - name: name
        value: lint
      - name: bundle
        value: quay.io/mytestworkload/build-definitions-test/task-lint:0.2@sha256:1866392f1fa1655ab09fe8325d69499b82e9fa3dd6ce667f042ce072d4a49df1
      - name: kind
        value: task
      resolver: bundles
    params:
    - name: verbosity
      value: -vv
    runAfter:
    - clone
