apiVersion: tekton.dev/v1
kind: Pipeline
metadata:
  name: ci-pipeline
spec:
  tasks:
  - name: clone
    params:
    - name: url
      value: "https://github.com/konflux-ci/pipeline-migration-tool"
    - name: depth
      value: "1"
    taskRef:
      params:
      - name: name
        value: clone
      - name: bundle
        value: quay.io/mytestworkload/build-definitions-test/task-clone:0.2@sha256:e9a2bc2e2ab045f75e6153617bf7040026634d0a370d930bfb6826eed112618b
      - name: kind
        value: task
      resolver: bundles
  - name: lint
    taskRef:
      params:
      - name: name
        value: lint
      - name: bundle
        value: quay.io/mytestworkload/build-definitions-test/task-lint:0.2@sha256:1866392f1fa1655ab09fe8325d69499b82e9fa3dd6ce667f042ce072d4a49df1
      - name: kind
        value: task
      resolver: bundles
    params:
    - name: verbosity
      value: -vv
    runAfter:
    - clone
